### ISSUE TITLE
from pgmpy.factors import TabularCPD causes ImportError: cannot import name 'TabularCPD'

### ISSUE THREAD

**Issue by djinnome** [pgmpy/pgmpy_notebook#11]
`from pgmpy.factors import TabularCPD`

causes the following ImportError:

`ImportError: cannot import name 'TabularCPD'`

This should be changed to:

`from pgmpy.factors.discrete import TabularCPD`

and then it works fine.

**Comment by OPzealot** [comment]
Thanks, it works.

**Comment by fgichuki** [comment]
Thanks you help is highly appreciated
