### ISSUE TITLE
Markov Models notebook and Approximate Inference notebooks are empty.

### ISSUE THREAD

**Issue by maruthimohan** [pgmpy/pgmpy_notebook#17]

**Comment by khalibartan** [comment]
@MaruthiMohanReddyPutha We haven't actually written those notebook till now. We will try to finish these notebook soon.

**Comment by chrism2671** [comment]
+1; even 10 lines of examples would be very helpful here

**Comment by khalibartan** [comment]
@chrism2671 We will try to work on those whenever we get time. If you want to see the API you can use our docs http://pgmpy.org/
