### ISSUE TITLE
Joint Probability over multiple variables using VariableElimination

### ISSUE THREAD

**Issue by huisophiewang** [pgmpy/pgmpy_notebook#19]
Hi,

I'm using pgmpy for my research project. It works very well for me. There is one problem though, I want to compute the joint probability of Pr(A,B,C|D,E), the query function of VariableElimination estimator returns 3 factors instead of one joint factor. I assume the 3 factors are marginal probability, but I think returning joint probability would make more sense. You can compute marginal probability from joint probability, but not vice versa. 

I found a post about the same issue (https://github.com/pgmpy/pgmpy/issues/250). Have you already added this feature? If so, could you please point the place to me?

Thank you!
Hui

**Comment by Sandy4321** [comment]
yes it would be nice to solve this problem

**Comment by ankurankan** [comment]
This has already been fixed. Now the `joint` parameter can be passed to the `query` method to specify whether to return a joint distribution or marginal distributions.
