### ISSUE TITLE
ipython notebook format

### ISSUE THREAD

**Issue by alisianoi** [pgmpy/pgmpy_notebook#2]
When I open these `.ipynb` files, I get a message that they are of version `v3` and have been automatically converted to `v4`.

I also noticed that the embedded `.png` images do not fit into their respective cells (possibly due to convert). And when I ran the code, there were several tracebacks.

Would you like to transition to `v4`, fix images and, possibly, code?

**Comment by ankurankan** [comment]
@all3fox: Yes we would definitely want to do this. But this is not a burning issue right now.

**Comment by ankurankan** [comment]
Fixed.
