### ISSUE TITLE
ImportError: cannot import name 'DiscreteFactor' from 'pgmpy.factors' 

### ISSUE THREAD

**Issue by stasonhan** [pgmpy/pgmpy_notebook#32]
ImportError: cannot import name 'DiscreteFactor' from 'pgmpy.factors'

**Comment by ankurankan** [comment]
@stasonhan It should be `from pgmpy.factors.discrete import DiscreteFactor`. Could you also tell me which notebook has the wrong statement?

**Comment by MeghaNarjary** [comment]
ImportError:cannot import name 'Factor' from 'pgmpy.factors'
