### ISSUE TITLE
Learning Markov Models

### ISSUE THREAD

**Issue by divyat09** [pgmpy/pgmpy_notebook#33]
Does pgmpy provide methods for fitting/inference in a Markov Model? I could not find them in the documentation of pgmpy, please let me know if there ways to perform exact or approximate inference in case of a Markov Model.

**Comment by ankurankan** [comment]
@divyat09 You can do exact inference for Markov Models using either Belief Propagation or Variable Elimination. But we don't have support for fitting for Markov Models yet.

**Comment by divyat09** [comment]
Thanks for your reply.
