### ISSUE TITLE
Compatibility issues 

### ISSUE THREAD

**Issue by johnasbaghi** [pgmpy/pgmpy_notebook#34]
I am having the hardest time inferring the specific versions of the libraries used to run the code in notebooks. Is there anyway you could add a requirements.txt file?

**Comment by ankurankan** [comment]
@athinggoingon Sorry about that. I will try to add a requirements file ASAP.

**Comment by ankurankan** [comment]
@athinggoingon I have added a requirements file. But there still might be some errors in the notebooks as they haven't been updated to the latest versions of pgmpy.
