### ISSUE TITLE
something wrong with Bayesian Networks

### ISSUE THREAD

**Issue by xhowdonewd** [pgmpy/pgmpy_notebook#45]
`
cpd_d = TabularCPD(variable='D', variable_card=2, values=[[0.6, 0.4]])     
cpd_i = TabularCPD(variable='I', variable_card=2, values=[[0.7, 0.3]])
`
should be
`
cpd_d = TabularCPD(variable='D', variable_card=2, values=[[0.6], [0.4]])      
cpd_i = TabularCPD(variable='I', variable_card=2, values=[[0.7], [0.3]])
`

**Comment by ankurankan** [comment]
@niudaohong Thanks for reporting this. Has been fixed now.
